name: Upload files to S3

on:
  push:
    branches:
    - main

env:
  MY_AWS_REGION: 'ap-northeast-1'
  AWS_ROLENAME: 'GithubActions_S3_Role'
  AWS_S3_BUCKET: 'chatgptlogs.azunyan.io'
  SOURCE_DIR: '.'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials with IAM Role
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/${{env.AWS_ROLENAME}}
        aws-region: ${{env.MY_AWS_REGION}}
    - name: Copy files to S3
      run: |
          aws s3 sync ${{env.SOURCE_DIR}} s3://${{env.AWS_S3_BUCKET}}/ --exclude '.*git*'
